name: dhall-to-python-package

dependencies:
  - base == 4.*
  - casing == 0.1.4.1
  - containers == 0.6.6
  - dhall == 1.41.2
  - filepath
  - text
  - megaparsec >= 9.2.1
  - directory >= 1.3.6.0
  - optparse-applicative >= 0.16.1.0

# verbatim:
  # default-language: GHC2021

library:
  source-dirs: src
  # exposed-modules: ReadWrite DhallExprUtils
  default-extensions:
    - OverloadedStrings
    - ScopedTypeVariables
  # verbatim:
    # default-language: GHC2021

executables:
  dhall-to-python:
    main: Main.hs
    dependencies:
      - dhall-to-python-package
    default-extensions:
      - OverloadedStrings
      - ExistentialQuantification
    # verbatim:
    #   default-language: GHC2021

  show-dhall-expr:
    main: ShowDhallExpr.hs
    dependencies:
      - dhall-to-python-package
    default-extensions:
      - OverloadedStrings
      - ExistentialQuantification
    # verbatim:
      # default-language: GHC2021

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - HUnit >= 1.6.0.0
      - megaparsec >= 9.2.1
    build-tools: hspec-discover
    default-extensions:	OverloadedStrings
    # verbatim:
      # default-language: GHC2021
